"""C21(v) -- the contamination calculus applied to a FRESH pattern:
cousin-pair races (n, n+4) mod 5 and mod 8.

General principle (prime-power contamination calculus): for the pattern
(n, n+d) and modulus m, enumerate the prime-square orientations
(q^2 - d, q^2) and (q^2, q^2 + d) surviving all local obstructions;
their residue classes mod m receive Lambda-weighted contamination, so
the corresponding UNWEIGHTED pattern counts are depressed there, and
the uncontaminated symmetric classes lead by exactly the removed mass.

For d = 4 the calculus gives predictions with no free choices:
  * orientation (q^2-4, q^2) is DEAD: q^2-4 = (q-2)(q+2) is composite
    for q > 3 (algebraic null, like C8);
  * orientation (q^2, q^2+4) SURVIVES (3 never divides q^2+4);
  * mod 5: q^2+4 prime forces q = +-2 (5), so the contaminated start
    class is q^2 = 4 (5).  Cousin starts lie in {2,3,4} mod 5; predict
        D5(x) = (pi_c(x;5,2)+pi_c(x;5,3))/2 - pi_c(x;5,4)
              = T_c(x) + noise,
        T_c(x) = (1/log^2 x) sum_{q<=sqrt x, q^2+4 prime} log q log(q^2+4);
  * mod 8: q odd gives q^2 = 1 (8): the ENTIRE deterministic term falls
    on start class 1; predict
        D8(x) = (1/3) sum_{a in {3,5,7}} pi_c(x;8,a) - pi_c(x;8,1)
              = T_c(x) + noise,
    while classes {3,5,7} are mutually symmetric (controls).

These are new predictions generated by the calculus, not fitted to data.
"""
import os, sys, math
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "engine"))
import numpy as np
from ntlib import *

X = int(float(sys.argv[1])) if len(sys.argv) > 1 else 10**9

c5 = {2: 0, 3: 0, 4: 0}
c8 = {1: 0, 3: 0, 5: 0, 7: 0}
snap = []
carry = np.zeros(4, dtype=bool)
carry_lo = 0
with Timer("sweep"):
    for lo, hi, seg in seg_sieve(X + 5, seg_size=1 << 22):
        comb = np.concatenate([carry, seg]) if lo else seg
        base = carry_lo if lo else 0
        starts = np.nonzero(comb[:-4] & comb[4:])[0] + base
        starts = starts[starts > 7]
        r5 = starts % 5
        for cls in (2, 3, 4):
            c5[cls] += int(np.count_nonzero(r5 == cls))
        r8 = starts % 8
        for cls in (1, 3, 5, 7):
            c8[cls] += int(np.count_nonzero(r8 == cls))
        snap.append((hi, c5[2], c5[3], c5[4], c8[1], c8[3], c8[5], c8[7]))
        carry, carry_lo = seg[-4:].copy(), hi - 4


def T_c(x):
    s = 0.0
    for q in primes_up_to(int(math.isqrt(int(x)))):
        q = int(q)
        if q > 2 and is_prime(q * q + 4):
            s += math.log(q) * math.log(q * q + 4)
    return s / math.log(x) ** 2


snap = np.array(snap, dtype=float)
x = snap[:, 0]
D5 = (snap[:, 1] + snap[:, 2]) / 2 - snap[:, 3]
D8 = (snap[:, 5] + snap[:, 6] + snap[:, 7]) / 3 - snap[:, 4]
ctrl23 = snap[:, 1] - snap[:, 2]                 # classes 2 vs 3 mod 5
ctrl35 = snap[:, 5] - snap[:, 6]                 # classes 3 vs 5 mod 8
w = np.diff(np.log(x), prepend=math.log(max(x[0] / 2, 2)))
lead5 = float(np.sum(w * (D5 > 0)) / np.sum(w))
lead8 = float(np.sum(w * (D8 > 0)) / np.sum(w))
print("final mod-5 classes (2,3,4): %d %d %d" % tuple(snap[-1, 1:4]))
print("final mod-8 classes (1,3,5,7): %d %d %d %d" % tuple(snap[-1, 4:8]))
rows = []
for i in sorted({min(len(x) - 1, int(len(x) * f) - 1) for f in (0.1, 0.4, 1.0)}):
    T = T_c(x[i])
    noise = math.sqrt(sum(snap[i, 1:4]))
    rows.append({"x": float(x[i]), "D5": float(D5[i]), "D8": float(D8[i]),
                 "T_pred": round(T, 1), "noise": round(noise, 1),
                 "ctrl23": float(ctrl23[i]), "ctrl35": float(ctrl35[i])})
    print("x=%.1e  D5=%+d (pred %+.0f)  D8=%+d (pred %+.0f)  noise ~%.0f  "
          "controls: 2-3: %+d, 3-5(8): %+d"
          % (x[i], D5[i], T, D8[i], T, noise, ctrl23[i], ctrl35[i]))
print("log-density of leadership: D5>0: %.3f   D8>0: %.3f" % (lead5, lead8))
save_result("c21c", {"conjecture": "contamination calculus, fresh instance: cousin races "
                                   "(n,n+4) mod 5 (class-4 deficit) and mod 8 (class-1 deficit)",
                     "X": X, "final_mod5": {str(k): v for k, v in c5.items()},
                     "final_mod8": {str(k): v for k, v in c8.items()},
                     "table": rows, "lead5": lead5, "lead8": lead8})
